### ISSUE TITLE
Default path is not relative to the script

### ISSUE THREAD

**Issue by ggomez91** [mathisonian/simple-testing-server#3]
If you dont specify --path it looks for files as absolute paths and not relative to the script. This is fixed by setting FILE_PREFIX = "." for default.

**Comment by mathisonian** [comment]
Thanks Gustavo,

Can you submit a PR for this and I'll merge?

Thanks
Matt

**Comment by asandwhich** [comment]
This is fixed by #4 , the PR I just submitted.

**Comment by mathisonian** [comment]
merged. thanks @asandwhich!
